name: Smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Create CI .env
        run: |
          cat > .env <<'EOF'
          MONGO_URI=mongodb://127.0.0.1:27017/messageboard?directConnection=true
          JWT_SECRET=ci-please-change
          PORT=3000
          SEND_REPORT_EMAILS=0
          ALLOW_PROMOTE=0
          EOF
          echo "Created .env for CI:"
          sed 's/JWT_SECRET=.*/JWT_SECRET=***redacted***/' .env

      - name: Start server
        run: |
          node server.js > server.log 2>&1 &
          echo "Booting server and waiting for port 3000…"
          npx --yes wait-on@7 http-get://127.0.0.1:3000

      - name: Run smoke tests
        run: node scripts/smoke.mjs

      - name: Upload server log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log
